version: "3.9"
services:
    app:
        image: golang:1.18
        container_name: go_test_dev
        command: sh -c "go mod download && go run main.go"
        ports:
            - 8081:8080
        working_dir: /app
        volumes:
            - ./:/app
        networks:
            - net
    db:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        container_name: go_test_dev_db
        volumes:
            - db:/data/db
        networks:
            - net
volumes:
    db:
networks:
  net: {}

